# Generated by Django 5.2.17 on 2026-09-23 17:08

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
